# Generated by Django 4.2.3 on 2023-12-18 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QUE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions', models.CharField(max_length=255)),
                ('optionA', models.CharField(max_length=255)),
                ('optionB', models.CharField(max_length=255)),
                ('optionC', models.CharField(max_length=255)),
                ('optionD', models.CharField(max_length=255)),
                ('correct', models.CharField(max_length=255)),
                ('correct_answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
            ],
        ),
        migrations.AlterField(
            model_name='answers',
            name='is_correct',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
