# Generated by Django 4.2.3 on 2023-12-18 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_answers_question_delete_que_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='correct',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='optionA',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='optionB',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='optionC',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='optionD',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='questions',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
